use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Public events that can be ingested into the world.
///
/// **Inputs-only** (ADR-0003). System-derived effects like relevance
/// updates or recommendations are not Events; they are
/// [`crate::ChangeRecord`]s, regenerated by replay. The log only stores
/// what the user or outside world said happened.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum WorldEvent {
    ProjectCreated {
        id: String,
        name: String,
        #[serde(default)]
        tags: Vec<String>,
    },
    /// Patch an existing project. Only fields with `Some(_)` are updated.
    /// `tags`, if provided, *replaces* the project's tag list.
    ProjectUpdated {
        id: String,
        #[serde(default)]
        name: Option<String>,
        #[serde(default)]
        tags: Option<Vec<String>>,
    },
    GoalCreated {
        id: String,
        name: String,
        #[serde(default)]
        tags: Vec<String>,
        #[serde(default = "default_importance")]
        importance: f32,
    },
    /// Patch an existing goal. Only fields with `Some(_)` are updated.
    /// `tags`, if provided, *replaces* the goal's tag list.
    GoalUpdated {
        id: String,
        #[serde(default)]
        name: Option<String>,
        #[serde(default)]
        tags: Option<Vec<String>>,
        #[serde(default)]
        importance: Option<f32>,
    },
    SignalObserved {
        source: String,
        summary: String,
        #[serde(default)]
        tags: Vec<String>,
        confidence: f32,
        #[serde(default)]
        observed_at: Option<DateTime<Utc>>,
    },
    /// Soft-shelve a project. Systems skip it; inspect still works.
    /// Reversible via [`WorldEvent::ProjectReactivated`].
    ProjectArchived {
        id: String,
        #[serde(default)]
        reason: Option<String>,
    },
    /// Mark a project done. Systems skip it; inspect still works.
    /// Reversible via [`WorldEvent::ProjectReactivated`].
    ProjectCompleted {
        id: String,
        #[serde(default)]
        note: Option<String>,
    },
    ProjectReactivated {
        id: String,
    },
    /// A first-class no-op event whose only effect is to advance
    /// event-log time. Lets [`Decay`](../docs/CONTEXT.md#decay) fire
    /// during quiet stretches (vacation, low signal activity) without
    /// breaking replay determinism. Ingested via `liferuntime pulse`.
    TimePulseObserved {
        observed_at: DateTime<Utc>,
    },
}

fn default_importance() -> f32 {
    0.5
}
