use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Public events that can be ingested into the world.
///
/// **Inputs-only** (ADR-0003). System-derived effects like relevance
/// updates or recommendations are not Events; they are
/// [`crate::ChangeRecord`]s, regenerated by replay. The log only stores
/// what the user or outside world said happened.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum WorldEvent {
    ProjectCreated {
        id: String,
        name: String,
        #[serde(default)]
        tags: Vec<String>,
    },
    /// Patch an existing project. Only fields with `Some(_)` are updated.
    /// `tags`, if provided, *replaces* the project's tag list.
    ProjectUpdated {
        id: String,
        #[serde(default)]
        name: Option<String>,
        #[serde(default)]
        tags: Option<Vec<String>>,
    },
    GoalCreated {
        id: String,
        name: String,
        #[serde(default)]
        tags: Vec<String>,
        #[serde(default = "default_importance")]
        importance: f32,
    },
    /// Patch an existing goal. Only fields with `Some(_)` are updated.
    /// `tags`, if provided, *replaces* the goal's tag list.
    GoalUpdated {
        id: String,
        #[serde(default)]
        name: Option<String>,
        #[serde(default)]
        tags: Option<Vec<String>>,
        #[serde(default)]
        importance: Option<f32>,
    },
    SignalObserved {
        source: String,
        summary: String,
        #[serde(default)]
        tags: Vec<String>,
        confidence: f32,
        #[serde(default)]
        observed_at: Option<DateTime<Utc>>,
    },
    /// Soft-shelve a project. Systems skip it; inspect still works.
    /// Reversible via [`WorldEvent::ProjectReactivated`].
    ProjectArchived {
        id: String,
        #[serde(default)]
        reason: Option<String>,
    },
    /// Mark a project done. Systems skip it; inspect still works.
    /// Reversible via [`WorldEvent::ProjectReactivated`].
    ProjectCompleted {
        id: String,
        #[serde(default)]
        note: Option<String>,
    },
    ProjectReactivated {
        id: String,
    },
    /// A first-class no-op event whose only effect is to advance
    /// event-log time. Lets [`Decay`](../docs/CONTEXT.md#decay) fire
    /// during quiet stretches (vacation, low signal activity) without
    /// breaking replay determinism. Ingested via `liferuntime pulse`.
    TimePulseObserved {
        observed_at: DateTime<Utc>,
    },
    /// Mark a goal as reached. Removes it from matching amplification.
    GoalAchieved {
        id: String,
        #[serde(default)]
        note: Option<String>,
    },
    /// Mark a goal as given up. Removes it from matching amplification.
    GoalAbandoned {
        id: String,
        #[serde(default)]
        reason: Option<String>,
    },
    /// Move an Achieved or Abandoned goal back to Active.
    GoalReactivated {
        id: String,
    },
    /// A user-recorded strategic Decision (ADR-0008).
    ///
    /// `chose` is the committed-to Project. `over` is a narrative-only
    /// list of considered rivals — **no mechanical effect**, surfaced
    /// later by `explain` / `decision list`. `dampen` is the explicit
    /// mechanical suppression set; per ADR-0008 these are deliberately
    /// separate so users can record "I chose TNT over Side-X" without
    /// silently muting Side-X.
    ///
    /// In this slice (issue #1) the event is plumbed through ingest,
    /// validation, and replay with **no derived effects**. Stance
    /// derivation, boost, and dampening land in issues #2..#6.
    ///
    /// `decided_at` is optional; when absent, downstream systems read
    /// the envelope's `occurred_at` (the runtime's ingest time, or the
    /// explicit `ingest_at` timestamp in tests).
    DecisionRecorded {
        chose: String,
        #[serde(default)]
        over: Vec<String>,
        #[serde(default)]
        dampen: Vec<String>,
        #[serde(default)]
        reason: Option<String>,
        #[serde(default)]
        decided_at: Option<DateTime<Utc>>,
    },
    /// Revoke a previously-recorded Decision (ADR-0008
    /// `#lifecycle`).
    ///
    /// `decision_id` references a `DecisionRecorded` event id. Ingest
    /// rejects unknown ids loudly (the user is asking the system to
    /// revoke nothing). Replay, by contrast, silently ignores an
    /// orphan revoke — consistent with the existing replay tolerance
    /// for impossible updates in `apply_event`, and required for any
    /// hand-corrupted log to keep loading.
    ///
    /// On apply, every Project whose current `DecisionStance` is owned
    /// by `decision_id` is cleared. Projects that were originally
    /// steered by this Decision but have since been superseded by a
    /// later one are unaffected — their stance is owned by the later
    /// Decision.
    DecisionRevoked {
        decision_id: liferuntime_event_log::EventId,
    },
}

fn default_importance() -> f32 {
    0.5
}
